#!/bin/bash
# +----------------------------------------------------------------------------+
# | MyFarm v0.3 * Web interface for remote monitoring MMxD devices             |
# | Copyright (C) 2019-2022 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | prepare                                                                    |
# | Prepare install                                                                 |
# +----------------------------------------------------------------------------+
#
#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

SWN="MyFarm Client"
SWV=`cat documents/VERSION`

clear
echo "--------------------------------------------------------------------------------"
echo "$SWN $SWV prepare installation"
echo "Copyright (C) 2019-2022 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>"
echo "--------------------------------------------------------------------------------"
echo "Installing required components..."
sudo apt-get install libdata-uuid-perl \
                     libwww-perl \
                     libwww-mechanize-perl

echo -e "\nDone."
