#!/bin/bash
# +----------------------------------------------------------------------------+
# | MyFarm v0.3 * Web interface for remote monitoring MMxD devices             |
# | Copyright (C) 2019-2022 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | uninstall                                                                  |
# | Uninstaller script                                                         |
# +----------------------------------------------------------------------------+
#
#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

erase()
{
  sudo rm --force $1
  echo "  $1"
}

erasedir()
{
  sudo rmdir $1 2> /dev/null
  echo "  $1"
}

# constans
SWN="MyFarm Client"
SWV=`cat documents/VERSION`
INSTDIR=/usr/local
PRGDIR="myfarm-client"

# uninstaller
clear
echo "--------------------------------------------------------------------------------"
echo "$SWN $SWV uninstaller script"
echo "Copyright (C) 2019-2022 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>"
echo "--------------------------------------------------------------------------------"
sleep 1
echo "Uninstalling..."
echo "- removing files:"
erase "$INSTDIR/bin/$PRGDIR"
erase "$INSTDIR/share/doc/$PRGDIR/*"
erase "$INSTDIR/share/$PRGDIR/*"
erase "$INSTDIR/share/man/man1/$PRGDIR.1"
erase "$INSTDIR/share/man/man7/myfarm.cgi.7"
erase "/etc/cron.d/$PRGDIR"
sudo /etc/init.d/cron restart
echo "- removing directories:"
erasedir $INSTDIR/share/doc/$PRGDIR/
erasedir $INSTDIR/share/$PRGDIR/
echo "Done."
